Develop
vllogvinov/projectads pull request #1
Opened 2020-11-25 21:15 UTC by vllogvinov

2020-11-25 21:58 UTC, sania1801 commented on .env
> +EMAIL_PASSWORD = "Password"
Add EOF

2020-11-25 21:58 UTC, sania1801 commented on .idea/inspectionProfiles/Project_Default.xml
> +</component>
Add to .gitignore

2020-11-25 21:58 UTC, sania1801 commented on .idea/misc.xml
> +</project>
Add to .gitignore

2020-11-25 21:58 UTC, sania1801 commented on .idea/modules.xml
> +</project>
Add to .gitignore

2020-11-25 21:58 UTC, sania1801 commented on .rspec
> +--require spec_helper
Add to .gitignore

2020-11-25 21:58 UTC, sania1801 commented on .idea/projectads.iml
> +</module>
Add to .gitignore

2020-11-25 21:58 UTC, sania1801 commented on .idea/vcs.xml
> +</project>
Add to .gitignore

2020-11-25 21:58 UTC, sania1801 commented on app/admin/dashboard.rb
> +        small I18n.t("active_admin.dashboard_welcome.call_to_action")
Use '' instead "" if you don't use interpolation

2020-11-25 21:58 UTC, sania1801 commented on app/admin/announcements.rb
> +  # end
Remove unused comments

2020-11-25 21:58 UTC, sania1801 commented on app/admin/dashboard.rb
> +  end # content
Remove unsued comments

2020-11-25 21:58 UTC, sania1801 commented on app/admin/users.rb
> +  # end
remove unused comments

2020-11-25 21:58 UTC, sania1801 commented on app/assets/stylesheets/application.css
> +@import "bootstrap";
add EOF

2020-11-25 21:58 UTC, sania1801 commented on app/controllers/application_controller.rb
> +		end
Use two whitespaces for tabulation

2020-11-25 21:58 UTC, sania1801 commented on app/helpers/announcement_helper.rb
> +end
Unused modeul

2020-11-25 21:58 UTC, sania1801 commented on app/helpers/announcements_helper.rb
> +end
Unused module

2020-11-25 21:58 UTC, sania1801 commented on app/controllers/users_controller.rb
> +
use two whitespaces for tabulation

2020-11-25 21:58 UTC, sania1801 commented on app/models/ability.rb
> +    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
Remove unused comments

2020-11-25 21:58 UTC, sania1801 commented on app/models/ability.rb
> +       end
use two whitespaces for tabulation

2020-11-25 21:58 UTC, sania1801 commented on app/models/announcement.rb
> +end
https://github.com/rubocop-hq/rails-style-guide#macro-style-methods check these information for order, and use 2 whitespace for tabulation

2020-11-25 21:58 UTC, sania1801 commented on app/models/role.rb
> +	validates_inclusion_of :role_name, {in: [ADMIN_ROLE, USER_ROLE]}
use 2 whitespaces for tabulation

2020-11-25 21:58 UTC, sania1801 commented on app/models/user.rb
> +  # validates_presence_of :first_name
remove unused comments

2020-11-25 21:58 UTC, sania1801 commented on app/views/announcements/_announcement.json.jbuilder
> +json.url announcement_url(announcement, format: :json)
remove this file if you doesn't use it

2020-11-25 21:58 UTC, sania1801 commented on app/views/announcements/_form.html.erb
> +    <%= form.label :title, 'Name: ' %>
add I18n to a project

2020-11-25 21:58 UTC, sania1801 commented on app/views/announcements/_form.html.erb
> +    <%= form.label :content, 'Description: ' %>
like as previous

2020-11-25 21:58 UTC, sania1801 commented on app/views/announcements/_form.html.erb
> +    <%= form.label :announcement_type, 'Type: ' %>
see previous comment

2020-11-25 21:58 UTC, sania1801 commented on app/views/announcements/_form.html.erb
> +    <%= form.label :image, 'Image: ' %>
see previous comment

2020-11-25 21:58 UTC, sania1801 commented on app/views/announcements/_form.html.erb
> +    <%= form.submit 'Submit' %>
see previous comment

2020-11-25 21:58 UTC, sania1801 commented on app/views/announcements/edit.html.erb
> +<%= link_to 'Back', announcements_path %>
add EOF

2020-11-25 21:58 UTC, sania1801 commented on app/views/announcements/edit.html.erb
> +<h1>Editing Announcement</h1>
Add I18n

2020-11-25 21:58 UTC, sania1801 commented on app/views/announcements/index.html.erb
> +  </thead>
Use I18n

2020-11-25 21:58 UTC, sania1801 commented on app/views/announcements/index.html.erb
> +          <td><%= link_to 'Destroy', announcement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
Use I18n

2020-11-25 21:58 UTC, sania1801 commented on app/views/announcements/index.html.erb
> +<% end %>
Add EOF

2020-11-25 21:58 UTC, sania1801 commented on app/views/announcements/index.html.erb
> +  <%= link_to 'Sign up', new_user_registration_path %>
Use I18n

2020-11-25 21:58 UTC, sania1801 commented on app/views/announcements/index.json.jbuilder
> +json.array! @announcements, partial: "announcements/announcement", as: :announcement
Remove it if you doesn't use

2020-11-25 21:58 UTC, sania1801 commented on app/views/announcements/new.html.erb
> +<h1>New Announcement</h1>
Add I18n

2020-11-25 21:58 UTC, sania1801 commented on app/views/announcements/new.html.erb
> +<%= link_to 'Back', announcements_path %>
see previous

2020-11-25 21:58 UTC, sania1801 commented on app/views/announcements/show.html.erb
> +  <strong>Тип:</strong>
Use 18n

2020-11-25 21:58 UTC, sania1801 commented on app/views/announcements/show.html.erb
> +  <strong>Пользователь:</strong>
Use I18n

2020-11-25 21:58 UTC, sania1801 commented on app/views/announcements/show.html.erb
> +	<%= link_to 'Edit', edit_announcement_path(@announcement) %> |
Use 18n

2020-11-25 21:58 UTC, sania1801 commented on app/views/announcements/show.json.jbuilder
> +json.partial! "announcements/announcement", announcement: @announcement
Remove it if unused

2020-11-25 21:58 UTC, sania1801 commented on app/views/devise/confirmations/new.html.erb
> +    <%= f.submit "Resend confirmation instructions" %>
Add I18n

2020-11-25 21:58 UTC, sania1801 commented on app/views/devise/mailer/confirmation_instructions.html.erb
> +<p><%= link_to 'Confirm my account', confirmation_url(@resource, confirmation_token: @token) %></p>
Use 18n

2020-11-25 21:58 UTC, sania1801 commented on app/views/devise/mailer/email_changed.html.erb
> +<% end %>
Use I18n

2020-11-25 21:58 UTC, sania1801 commented on app/views/devise/mailer/password_change.html.erb
> +<p>We're contacting you to notify you that your password has been changed.</p>
Use 18n

2020-11-25 21:58 UTC, sania1801 commented on app/views/devise/mailer/reset_password_instructions.html.erb
> +<p>Your password won't change until you access the link above and create a new one.</p>
Use I18n

2020-11-25 21:58 UTC, sania1801 commented on app/views/devise/mailer/unlock_instructions.html.erb
> +<p><%= link_to 'Unlock my account', unlock_url(@resource, unlock_token: @token) %></p>
Use 18n

2020-11-25 21:58 UTC, sania1801 commented on app/views/devise/passwords/edit.html.erb
> +    <%= f.label :password, "New password" %><br />
I18n

2020-11-25 21:58 UTC, sania1801 commented on app/views/devise/passwords/edit.html.erb
> +<h2>Change your password</h2>
I18n

2020-11-25 21:58 UTC, sania1801 commented on app/views/devise/passwords/edit.html.erb
> +      <em>(<%= @minimum_password_length %> characters minimum)</em><br />
I18n

2020-11-25 21:58 UTC, sania1801 commented on app/views/devise/passwords/edit.html.erb
> +    <%= f.label :password_confirmation, "Confirm new password" %><br />
I18n

2020-11-25 21:58 UTC, sania1801 commented on app/views/devise/passwords/edit.html.erb
> +    <%= f.submit "Change my password" %>
I18n

2020-11-25 21:58 UTC, sania1801 commented on app/views/devise/passwords/new.html.erb
> +<h2>Forgot your password?</h2>
I18n

2020-11-25 21:58 UTC, sania1801 commented on app/views/devise/passwords/new.html.erb
> +    <%= f.submit "Send me reset password instructions" %>
I18n

2020-11-25 21:58 UTC, sania1801 commented on app/views/devise/registrations/edit.html.erb
> +<h2>Edit <%= resource_name.to_s.humanize %></h2>
Add i18n to this file

2020-11-25 21:58 UTC, sania1801 commented on app/views/devise/registrations/new.html.erb
> +<h2>Sign up</h2>
Add I18n to this file

2020-11-25 21:58 UTC, sania1801 commented on app/views/devise/sessions/new.html.erb
> +<h2>Log in</h2>
Add I18n to this one

2020-11-25 21:58 UTC, sania1801 commented on app/views/devise/shared/_links.html.erb
> +<%- if controller_name != 'sessions' %>
add I18n

2020-11-25 21:58 UTC, sania1801 commented on app/views/devise/unlocks/new.html.erb
> +<h2>Resend unlock instructions</h2>
Add I18n

2020-11-25 21:58 UTC, sania1801 commented on config/routes.rb
> +  	end
Use 2 whitespaces for tabulation

2020-11-25 21:58 UTC, sania1801 commented on config/routes.rb
>    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Remove it if you doesn't use

2020-11-25 21:58 UTC, sania1801 commented on config/webpack/environment.js
> +module.exports = environment
Add EOF

2020-11-25 21:58 UTC, sania1801 commented on db/seeds.rb
> +AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password') if Rails.env.development?
Add EOF

2020-11-25 21:58 UTC, sania1801 commented on db/seeds.rb
> +
Move email and password and password_confirmation in credentials

2020-11-25 21:58 UTC, sania1801 commented on spec/factories/announcements.rb
> +	end
Use 2 whitespaces for tabulation

2020-11-25 21:58 UTC, sania1801 commented on spec/factories/announcements.rb
> +end
Add EOF

2020-11-25 21:58 UTC, sania1801 commented on spec/factories/users.rb
> +    last_name { Faker::Name.last_name }
Use 2 whitespaces for tabulation

2020-11-25 21:58 UTC, sania1801 commented on spec/factories/users.rb
> +	end
like as a previous

2020-11-25 21:58 UTC, sania1801 commented on spec/factories/users.rb
> +end
add EOF

2020-11-25 21:58 UTC, sania1801 commented on spec/models/announcement_spec.rb
> +  end
Use 2 whitespaces for tabulation

2020-11-25 21:58 UTC, sania1801 commented on spec/models/announcement_spec.rb
> +  describe "status_changing" do
Try to use '' instead ""

2020-11-25 21:58 UTC, sania1801 commented on spec/models/announcement_spec.rb
> +  describe "validate_presence_adv" do
Try to use '' instead ""

2020-11-25 21:58 UTC, sania1801 commented on spec/models/role_spec.rb
> +	describe "validate_roles" do
Try to use '' instead ""

2020-11-25 21:58 UTC, sania1801 commented on spec/models/role_spec.rb
> +	end
Use 2 whitespaces for tabulation

2020-11-25 21:58 UTC, sania1801 commented on spec/requests/users_request_spec.rb
> +RSpec.describe "Users", type: :request do
Remove it if you doesn't use, but the better add test for this controller

2020-11-25 21:58 UTC, sania1801 commented on test/controllers/announcements_controller_test.rb
> +end
Move to spec

2020-11-25 21:58 UTC, sania1801 commented on test/fixtures/admin_users.yml
> +# column: value
Remove it

2020-11-25 21:58 UTC, sania1801 commented on test/fixtures/announcements.yml
> +  status: two
Use specs instead default rails tests

2020-11-25 21:58 UTC, sania1801 commented on test/fixtures/users.yml
> +# column: value
Remove it

2020-11-25 21:58 UTC, sania1801 commented on test/models/admin_user_test.rb
>    #   assert true
Move to spec or remove it if you doesn't use

2020-11-25 21:58 UTC, sania1801 commented on test/models/announcement_test.rb
>    # end
Remove

2020-11-25 21:58 UTC, sania1801 commented on test/system/announcements_test.rb
> +end
Move to spec

2021-01-02 22:08 UTC, sania1801 requested changes

2021-01-02 22:08 UTC, sania1801 commented on Gemfile
> +gem "rubycritic", require: false
Use '' instead of using ""

2021-01-02 22:08 UTC, sania1801 commented on Gemfile
> +  gem "letter_opener"
Looks previous comment

2021-01-02 22:08 UTC, sania1801 commented on app/admin/announcements.rb
> +      link_to 'Approve', admin_announcement_path(announcement: {status: "approved"}), method: :patch if announcement.ready_to_publish?
Use '' instead of ""

2021-01-02 22:08 UTC, sania1801 commented on app/admin/announcements.rb
> +      link_to 'Reject', admin_announcement_path(announcement: {status: "rejected"}), method: :patch if announcement.ready_to_publish?
Use '' instead of ""

2021-01-02 22:08 UTC, sania1801 commented on app/assets/stylesheets/active_admin.scss
> +@import "active_admin/mixins";
Use '' instead of ""

2021-01-02 22:08 UTC, sania1801 commented on app/assets/stylesheets/active_admin.scss
> +@import "active_admin/base";
Use '' instead of ""

2021-01-02 22:08 UTC, sania1801 commented on app/assets/stylesheets/active_admin.scss
> +    }
Improve identations

2021-01-02 22:08 UTC, sania1801 commented on app/assets/stylesheets/active_admin.scss
> +//   .status_tag { background: #6090DB; }
Remove it

2021-01-02 22:08 UTC, sania1801 commented on app/controllers/announcements_controller.rb
> +    @announcements = Announcement.published.includes(image_attachment: :blob).page(params[:page]).per(6).desc_order
```suggestion
    @announcements = Announcement.published.desc_order.includes(image_attachment: :blob).page(params[:page]).per(6)
```

2021-01-02 22:08 UTC, sania1801 commented on app/controllers/announcements_controller.rb
> +      flash[:notice] = 'Your announcement does not comply with the publication rules and has been rejected. You can edit it and try again. '
Move it in I18n

2021-01-02 22:08 UTC, sania1801 commented on app/controllers/announcements_controller.rb
> +  end
```suggestion
  def create
    @announcement = current_user.announcements.new(announcement_params)
    @announcement.send_to_moderate
    if params[:post_button].present?
    respond_to do |format|
      if @announcement.save
        format.html { redirect_to @announcement, notice: 'Announcement was successfully created.' }
        format.json { render :show, status: :created, location: @announcement }
      else
        format.html { render :new }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end
```

2021-01-02 22:08 UTC, sania1801 commented on app/controllers/announcements_controller.rb
> +        @announcement.send_to_moderate! if params[:post_button].present?
Move it in particular method inside model

2021-01-02 22:08 UTC, sania1801 commented on app/models/announcement.rb
> +
Remove this lines

2021-01-02 22:08 UTC, sania1801 commented on app/models/announcement.rb
> +
Remove line

2021-01-02 22:08 UTC, sania1801 commented on app/models/announcement.rb
> +  paginates_per 6
Only one whitespace, need into two

2021-01-02 22:08 UTC, sania1801 commented on app/models/announcement.rb
> +
Remove line

2021-01-02 22:08 UTC, sania1801 commented on app/views/announcements/_form.html.erb
> +    <%= form.label :image, 'Image: ' %>
```suggestion
    <%= form.label :image, 'Image:&nbsp' %>
```

2021-01-02 22:08 UTC, sania1801 commented on app/views/announcements/_form.html.erb
> +<div class="flex-buttons" style="display:flex;">
Move style for this one into css file

2021-01-02 22:08 UTC, sania1801 commented on app/views/announcements/_form.html.erb
> +  <% if @announcement.draft? || @announcement.rejected? %>
Move to helper

2021-01-02 22:08 UTC, sania1801 commented on app/views/announcements/index.html.erb
> +        <td><div style="width: 60px; height:auto"><%= image_tag(announcement.image, style: "width:100%") if announcement.image.attached? %></div></td>
Move to css file

2021-01-02 22:08 UTC, sania1801 commented on app/views/announcements/show.html.erb
> +<div style="width:400px; height:auto">
Move to css

2021-01-02 22:08 UTC, sania1801 commented on app/views/announcements/show.html.erb
> +	<%= link_to image_tag(@announcement.image, style: "width:100%"), announcements_path if @announcement.image.attached? %>
Move to css

2021-01-02 22:08 UTC, sania1801 commented on app/views/announcements/show.html.erb
> +  <% if can? :update, @announcement %>
Join two condition in one if,and move it into helper

2021-01-02 22:08 UTC, sania1801 commented on app/views/users/announcements.html.erb
> +        <td><div style="width: 60px; height:auto"><%= image_tag(announcement.image, style: "width:100%") if announcement.image.attached? %></div></td>
Move styles to css

2021-01-02 22:08 UTC, sania1801 commented on config/initializers/phonelib.rb
> +Phonelib.default_country = "BY"
Use '' instead ""

2021-01-02 22:08 UTC, sania1801 commented on config/routes.rb
> +  root "announcements#index"
Use '' instead ""

2021-01-02 22:08 UTC, sania1801 commented on spec/spec_helper.rb
> +SimpleCov.start
Remove it, you use it into rails_helper

2021-01-02 22:22 UTC, sania1801 requested changes

2021-01-02 22:22 UTC, sania1801 commented on spec/models/announcement_spec.rb
> +  	it "status_changing" do
Try to use '' instead ""

2021-01-06 20:30 UTC, sania1801 commented on Rakefile
>  # for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.
remove it

2021-01-06 20:30 UTC, sania1801 commented on app/admin/dashboard.rb
> +    # end
remove it

2021-01-12 19:54 UTC, vllogvinov commented on app/models/role.rb
> +	validates_inclusion_of :role_name, {in: [ADMIN_ROLE, USER_ROLE]}
File was deleted as unused.

2021-01-23 11:29 UTC, sania1801 requested changes

2021-01-23 11:29 UTC, sania1801 commented on app/admin/users.rb
> +ActiveAdmin.register User do
permit_params?

2021-01-23 11:29 UTC, sania1801 commented on app/channels/application_cable/channel.rb
>    class Channel < ActionCable::Channel::Base
Remove if don't use it

2021-01-23 11:29 UTC, sania1801 commented on app/channels/application_cable/connection.rb
>    end
Remove if don't use it

2021-01-23 11:29 UTC, sania1801 commented on app/controllers/announcements_controller.rb
> +  # GET /announcements.json
Remove this comments it's not nedded in all views

2021-01-23 11:29 UTC, sania1801 commented on app/controllers/announcements_controller.rb
> +    @announcements = Announcement.published.desc_order.includes(image_attachment: :blob).page(params[:page]).per(6)
use constant for 6

2021-01-23 11:29 UTC, sania1801 commented on app/controllers/announcements_controller.rb
> +      flash[:notice] = 'Your announcement does not comply with the publication rules
I18n

2021-01-23 11:29 UTC, sania1801 commented on app/controllers/announcements_controller.rb
> +        format.html { redirect_to @announcement, notice: 'Announcement was successfully created.' }
I18n

2021-01-23 11:29 UTC, sania1801 commented on app/controllers/announcements_controller.rb
> +      format.html { redirect_to announcements_url, notice: 'Announcement was successfully destroyed.' }
I18n

2021-01-23 11:29 UTC, sania1801 commented on app/controllers/announcements_controller.rb
> +    @announcement = Announcement.find(params[:id])
```suggestion
    @announcement ||= Announcement.find(params[:id])
```

2021-01-23 11:29 UTC, sania1801 commented on app/controllers/users/confirmations_controller.rb
> +end
Remove comments

2021-01-23 11:29 UTC, sania1801 commented on app/controllers/users/omniauth_callbacks_controller.rb
> +    # end
remove comments

2021-01-23 11:29 UTC, sania1801 commented on app/controllers/users/passwords_controller.rb
> +    # end
remove comments

2021-01-23 11:29 UTC, sania1801 commented on app/controllers/users/registrations_controller.rb
> +    #   super
like as previous

2021-01-23 11:29 UTC, sania1801 commented on app/controllers/users/sessions_controller.rb
> +    # DELETE /resource/sign_out
remove this

2021-01-23 11:29 UTC, sania1801 commented on app/controllers/users/unlocks_controller.rb
> +    # end
like as a previous

2021-01-23 11:29 UTC, sania1801 commented on app/helpers/application_helper.rb
>  end
remove it

2021-01-23 11:29 UTC, sania1801 commented on app/helpers/users_helper.rb
>  end
remove it

2021-01-23 11:29 UTC, sania1801 commented on app/models/admin.rb
> +end
why we need to AdminUser?

2021-01-23 11:29 UTC, sania1801 commented on app/views/announcements/_form.html.erb
> +      <h2><%= pluralize(announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>
move to i18n

2021-01-23 11:29 UTC, sania1801 commented on app/views/announcements/_form.html.erb
> +<div class="flex-buttons" style="display:flex;">
Why we are need in style attribute?

2021-01-23 11:29 UTC, sania1801 commented on app/views/announcements/index.html.erb
> +        <td><div style="width: 60px; height:auto"><%= image_tag(announcement.image, style: "width:100%") if announcement.image.attached? %></div></td>
move style to css files

2021-01-23 11:29 UTC, sania1801 commented on app/views/announcements/show.html.erb
> +  <strong><%= "#{t('announcements.fields.phone')}: " %></strong>
```suggestion
  <strong><%= t('announcements.fields.phone')%>:</strong>
```

2021-01-23 11:29 UTC, sania1801 commented on app/views/announcements/show.html.erb
> +  <strong><%= "#{t('announcements.fields.content')}: " %></strong>
see below

2021-01-23 11:29 UTC, sania1801 commented on app/views/announcements/show.html.erb
> +  <strong><%= "#{t('announcements.fields.name')}: " %></strong>
see below

2021-01-23 11:29 UTC, sania1801 commented on app/views/announcements/show.html.erb
> +  <strong><%= "#{t('announcements.fields.type')}: " %></strong>
see below

2021-01-23 11:29 UTC, sania1801 commented on app/views/announcements/show.html.erb
> +  <%= link_to t('announcements.buttons.destroy'), @announcement, method: :delete, data: { confirm: 'Are you sure?' } %> |
move confirm to I18n

2021-01-23 11:29 UTC, sania1801 commented on app/views/users/announcements.html.erb
> +          <td><%= link_to t('announcements.buttons.destroy'), announcement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
move confirm to i18n

2021-01-23 11:29 UTC, sania1801 commented on bin/yarn
> +  exit 1
?

2021-02-02 21:40 UTC, merged